version: "3.8"

services:
  internet-monitor:
    build: .
    container_name: internet-monitor
    ports:
      - "5000:5000"   # Web UI
    volumes:
      - ./data:/data
    environment:
      MIN_DOWNLOAD: 20

      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_USER: test@example.com
      SMTP_PASS: test
      ALERT_EMAIL_TO: admin@example.com
    depends_on:
      - mailpit
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP
    restart: unless-stopped
